#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
server:
  #port: 8763
  port: 8988
spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://localhost:9411